### ISSUE TITLE
Brewing glibc

### ISSUE THREAD

**Issue by dpo** [Linuxbrew/brew#161]
```
$ cat /proc/version 
Linux version 3.10.0-229.14.1.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.3 20140911 (Red Hat 4.8.3-9) (GCC) ) #1 SMP Tue Sep 15 15:05:51 UTC 2015
$ uname -a
Linux amdahl 3.10.0-229.14.1.el7.x86_64 #1 SMP Tue Sep 15 15:05:51 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

I recently tried brewing `glibc` on the system above. The installation failed, complaining that `makeinfo` is not available. The `makeinfo` program is available as part of `texinfo`, but `brew install texinfo` failed because it apparently depends on `glibc` (though `brew deps` doesn't reveal it; I'm not sure what the gist of this is).

A solution was to ask the system administrator to `apt_get install texinfo`, which resolved the issue.

An additional difficulty is that brewing `glibc` fails if `LD_LIBRARY_PATH` contains something (glibc complains that the path shouldn't contain the current dir, but I found that I had to wipe it entirely for the build to complete.)

**Comment by sjackman** [comment]
> I recently tried brewing glibc on the system above. The installation failed, complaining that makeinfo is not available.

I haven't yet run into this `texinfo` dependency, which I find surprising. I'll see if I can reproduce it on Docker.

**Comment by sjackman** [comment]
> `brew install texinfo` failed because it apparently depends on `glibc` (though `brew deps` doesn't reveal it; I'm not sure what the gist of this is).

All bottles depend on `gcc` for `libstdc++.so.6` and `glibc` for `libc.so.6` if the host system provides `glibc` < 2.19. Please report the output of `brew config`

**Comment by sjackman** [comment]
> A solution was to ask the system administrator to apt_get install texinfo, which resolved the issue.

I'm glad the workaround was effective. I'd still like to figure out the root issue.

**Comment by sjackman** [comment]
> An additional difficulty is that brewing `glibc` fails if `LD_LIBRARY_PATH` contains something (glibc complains that the path shouldn't contain the current dir, but I found that I had to wipe it entirely for the build to complete.)

`brew doctor` will give you a warning if `LD_LIBRARY_PATH` is set. That warning should probably be more prominent. Arguable `LD_LIBRARY_PATH` should be cleared for `brew install`, I'm feeling more and more that's the correct solution, possibly with exposing a `HOMEBREW_LD_LIBRARY_PATH` to allow for workarounds that are occasionally needed. Alternatively, `brew install` can be loud and obnoxious if `LD_LIBRARY_PATH` is set.

Setting `LD_LIBRARY_PATH` causes all sorts of unpredictable breakage because it has a higher search priority than the `RPATH` encoded in executables that are built by Linuxbrew.

@rwhogg How should we deal with `LD_LIBRARY_PATH`?

**Comment by dpo** [comment]
> Arguable LD_LIBRARY_PATH should be cleared for brew install, I'm feeling more and more that's the correct solution, possibly with exposing a HOMEBREW_LD_LIBRARY_PATH to allow for workarounds that are occasionally needed.

Yes that also seems reasonable to me.
