### ISSUE TITLE
installing to /usr/local

### ISSUE THREAD

**Issue by jimmont** [Linuxbrew/brew#168]
_This is a question, not a bug._

1. What problems will I have installing to `/usr/local` (instead of `~/.linuxbrew/bin`)?
2. I want to make brew installed packages available to everyone, including root/sudoers. Is installing to `/usr/local` in this case preferred (over `~/.linuxbrew/bin`)?
3. My specific goal is to maintain many packages that are not part of Debian at their latest version (eg Nodejs stable) and make these available to all users/services. Is installing to `/usr/local` best for this scenario?

_Thank you._

**Comment by sjackman** [comment]
Hi, Jim.
1. The primary issue is that libraries installed in `/usr/local/lib` may be picked up by executables in `/usr/bin` which could potentially break them.
2. The recommended installation location for a shared Linuxbrew installation is `/home/linuxbrew/.linuxbrew` owned by the user `linuxbrew`.
3. Use `/home/linuxbrew/.linuxbrew`, which has the added benefit of being able to use non-relocatable precompiled binary bottles.

Cheers,
Shaun

**Comment by jimmont** [comment]
Thanks very much Shaun. A few followup questions due to my lack of understanding and knowledge.
1. Wouldn't this be unexpected behavior? Is `/usr/local` for Users? I thought that it was and might well be mistaken.
2. Good to know. I wonder (to myself) why I would setup another user when anyone can be in the sudo group?
3. I don't understand what a non-relocatable precompiled binary bottle means. I'll Google this but perhaps you can fill me in for the benefit of anyone who might have this same question and look through the issues first (as I did).

**Comment by sjackman** [comment]
1. Originally yes that was the intention, but these days not so much. Users typically install executables in `~/bin`. `/usr` is reserved the OS (like Ubuntu), and it's best not to use `/usr/local` (except on a single-user Mac, where Homebrew uses it by default).
2. So that you can add users to the `linuxbrew` sudo group without having to add them to the `root` sudo group.
3. Linuxbrew compiles binary executables (bottles, in brew parlance) for many formula. Some of these bottles are relocatable and can be installed in any location. Others are non-relocatable and can only be installed in `/home/linuxbrew/.linuxbrew`

**Comment by ylluminate** [comment]
@sjackman I'm curious of your mentioning `/home/linuxbrew`... If one has multiple users that the admin would like to have access to a central repo of installed linuxbrew installed utilities, is this the way to do it?  Do you have some instructions on this floating around?  It would be nice to have a `linuxbrew` group and then an admin could just add each users to the linuxbrew group and then they'd have access to `/home/linuxbrew/.linuxbrew` and just be able to brew install to that, etc. or I suppose the could customize their own and the `linuxbrew` user could just maintain that primary repo...

**Comment by sjackman** [comment]
I don't have any instructions, but it's pretty much as you say. Create a `linuxbrew` user that owns `/home/linuxbrew` and give users `sudo` access to the `/home/linuxbrew/.linuxbrew/bin/brew` executable as the user `linuxbrew`.

**Comment by sambrightman** [comment]
Is this recommendation still accurate now? The default script install location and homepage manual install suggestion are `~/.linuxbrew`, rather than `/home/linuxbrew/.linuxbrew`. Does this break unrelocatable bottles?

Both the method above and the current installer also require `sudo` (seemingly unnecessarily), which prevents people who truly lack root access from using it as recommended. It's not clear to me if I should try to submit a PR to avoid sudo on installation in light of the above recommendation and rumoured merger into main Homebrew repos.

**Comment by sjackman** [comment]
`/home/linuxbrew/.linuxbrew` is the recommended installation location to be able to use non-relocatable bottles, and `~/.linuxbrew` otherwise.
 
Thanks for the bug report, Sam. The installer is not intended to require `sudo`. I'll take a look at it. In the mean time, you can install without `sudo` using…
```sh
git clone https://github.com/Linuxbrew/brew ~/.linuxbrew
```
or if you do have `sudo`
```sh
sudo mkdir /home/linuxbrew
sudo chown $USER: /home/linuxbrew
git clone https://github.com/Linuxbrew/brew /home/linuxbrew/.linuxbrew
PATH=/home/linuxbrew/.linuxbrew/bin:$PATH
brew install hello
```

The precompiled binary bottles of non-relocatable bottles can only be used if you install in `/home/linuxbrew/.linuxbrew`, otherwise they have to be built from source. See the documentation below, but wherever it reads `/usr/local`, which is for macOS, read instead `/home/linuxbrew/.linuxbrew`.
+ http://docs.brew.sh/Installation.html#alternative-installs
+ http://docs.brew.sh/FAQ.html#why-do-you-compile-everything
+ http://docs.brew.sh/Bottles.html#cellar-cellar

**Comment by Char-Aznable** [comment]
I encounter a similar issue where I don't have root access and have to manually clone into ~/.linuxbrew I wonder if this is still a recommendation in the long term because one would like to be able to get reliable upgrade from bottles for package like glibc and this seems to create long term dependency issue if it requires installation in /home/llinuxbrew/.linuxbrew to get bottles. For example, if glibc gets updated at some point that a lot of packages depends on but its bottle can't be installed then the user is stuck. On the other hand, the build-from-source option doesn't seem reliable for linuxbrew and I've seen a lot of issues for building glibc itself. Any thoughts?

**Comment by sjackman** [comment]
`glibc` is unfortunately non-relocatable. Once it's installed, it can't be moved. It looks for config and data files in a fixed position that's determined at the time that it is compiled. For that reason, it has to be installed from source, unless the installation directory is `/home/linuxbrew/.linuxbrew`.

If it's an option for you, you could open a ticket with your systems department to ask that they create a `linuxbrew` role account with home directory `/home/linuxbrew` for the purpose of sharing software that is used by your group.

Alternatively you can use Docker or Singularity.

**Comment by Char-Aznable** [comment]
I talked to the system admin and it's not possible to allocate space under /home/linuxbrew but the best they can do is to create a symlink /home/linuxbrew to /other/directory so that linuxbrew's files are on /other/directory but pointed to by /home/linuxbrew. Would this be a solution?

**Comment by sjackman** [comment]
Yes, I believe that works. `brew doctor` may complain, but I think that it should work. It's possible that it still won't use non-relocatables bottles by default, but you can force it with
`brew install --force-bottle glibc`
