### ISSUE TITLE
Missing "compress" for .tar.Z files

### ISSUE THREAD

**Issue by tueda** [Linuxbrew/brew#187]
I encountered a build error like the following:
```
$ brew install wordplay
==> Downloading http://hsvmovies.com/static_subpages/personal_orig/wordplay/wordplay722.tar.Z
######################################################################## 100.0%
tar (child): compress: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
Error: Failure while executing: tar xf /localstore/theorie/tueda/build/linuxbrew/Cache/wordplay-7.22.tar.Z
```
Yes, the problem is that my system doesn't have `compress` to uncompress `.tar.Z`. Though I can try to install `compress` on the machine somehow, in this case one could consider `compress` as a build dependency for `.tar.Z` files. So it would be nice if Linuxbrew could handle this dependency automatically, like `xz` for `.tar.xz` files.

In practice, at least on Linux, I did't need to install `compress`; a symbolic link by `ln -s /usr/bin/gzip compress` in `$HOMEBREW_PREFIX/bin` did the job to me.

**Comment by sjackman** [comment]
The `gzip` formula installs an executable named `uncompress`. Oddly it doesn't install an executable named `compress`. Perhaps that's because gzip can extract `.Z` archives but can't create them (untested).

1. One option is to patch `tar` to use the `uncompress` executable rather than `compress`. That seems pretty reasonable to me.
2. On Debian `/usr/bin/compress` is provided by the package [ncompress](https://packages.debian.org/jessie/amd64/ncompress/filelist). We could package `ncompress` for Linuxbrew. https://github.com/vapier/ncompress

@rwhogg Which of these options do you prefer?
I'm leaning toward packaging `ncompress`, less hacky. I think I'll send it upstream to `Homebrew/dupes`.

**Comment by sjackman** [comment]
I've created a PR to add `ncompress` to `Homebrew/dupes`. https://github.com/Homebrew/homebrew-dupes/pull/682
If this PR is merged upstream, then we can add
```ruby
    when ".Z"         then Dependency.new("homebrew/dupes/ncompress", tags) unless OS.mac?
```
to https://github.com/Linuxbrew/brew/blob/master/Library/Homebrew/dependency_collector.rb#L182

**Comment by bw-yuhogg** [comment]
> @rwhogg Which of these options do you prefer?
I'm leaning toward packaging ncompress, less hacky. I think I'll send it upstream to Homebrew/dupes.

I'm good with `ncompress`.

In addition to compatibility with Debian (👍) and being less hacky (👍), the whole reason GZip exists is to avoid problems with the (now-expired) [LZW patents](https://en.wikipedia.org/wiki/Compress#History). While that's no longer *relevant* per se, messing with that seems perverse.

**Comment by bw-yuhogg** [comment]
@sjackman I think we can close this issue now.
