### ISSUE TITLE
feature: automatically flag suspicious formulas (eg OSX specific elements)

### ISSUE THREAD

**Issue by timotheecour** [Linuxbrew/brew#223]
How about having a `brew audit` variant that checks for suspicious formulas likely not to be cross-platform, eg:

in https://github.com/Homebrew/homebrew-science/pull/4834 I fixed the following bug:
```
args << "-DPYTHON_LIBRARY='#{python_prefix}/lib/lib#{python_version}.dylib'"

to:

dylib = OS.mac? ? "dylib" : "so"
args << "-DPYTHON_LIBRARY='#{python_prefix}/lib/lib#{python_version}.#{dylib}'"
```

This is fairly typical and we could have a tool to help identify (and potentially suggest fixes) a (growing list of) cases.

**Comment by bw-yuhogg** [comment]
I'm hesitant to adopt something like that in `brew audit` because we're trying to help Homebrew/brew improve its Linux support and I don't see them accepting it.

So how about this: make a similar tool (could even be partially copy-pasted from the current `audit.rb`) and submit it as a PR to the Linuxbrew/developer tap? I'd personally welcome such a tool and we can accept all kinds of PR's there since we're not burdened by compatibility with upstream.

@sjackman, do you agree?

**Comment by sjackman** [comment]
I think having the tool is a great idea. If it doesn't require duplicating a lot of code, then I think it code go in `linuxbrew/developer` named `cmd/audit-linux`, but only if it doesn't require copy-pasting dozens of lines. If it does, I think it should go in `Linuxbrew/brew`, although I do agree with your principle of avoiding further drift between Homebrew and Linuxbrew. Upstream may accept a patch that put the OS-specific improvements to `audit` in `extend/os/linux/dev-cmd/audit.rb`
