### ISSUE TITLE
Method for changing to brewed shell?

### ISSUE THREAD

**Issue by ylluminate** [Linuxbrew/brew#286]
Simply issuing a command such as `chsh -s /home/user/.linuxbrew/bin/zsh` is not sufficient for changing a shell. One has to add the shell to the shell options and/or edit the actual user's profile configuration.  Is there a preferred method to set up new shells the "LinuxBrew" way?

**Comment by sjackman** [comment]
As far as I know, you're on the right track of adding the shell to `/etc/shells` and using `chsh`.
Personally I configure my xterm to start `/home/user/.linuxbrew/bin/zsh` instead of the default user shell.

**Comment by emanresusername** [comment]
might be worth adding a check and change for that in the uninstall script or a warning in the info message?
one might take the shell so for granted that it wouldn't occur to them that it was tied to brew.
they might then uninstall the brew formula or otherwise play around with the brew install and [end up in a bad situation where they can't open a terminal](https://unix.stackexchange.com/questions/136964/cant-open-shell-after-changing-default-shell/136968#136968) . . . not that i ever did that or anything :sweat_smile:
