### ISSUE TITLE
Copy Linuxbrew Dir Structure?

### ISSUE THREAD

**Issue by jwhite007** [Linuxbrew/brew#302]
This isn't really an issue, per se.

I have a stable dir structure of linuxbrew which I want to maintain for our applications which are in production. I will not update the linuxbrew applications as often in this dir tree.

We also have applications in development. I would like a different linuxbrew dir structure for these. This tree I will update more often.

I have something like /path/to/prod/.linuxbrew. I would also like /path/to/dev/.linuxbrew. I know that I can `git clone /path/to/prod/.linuxbrew /path/to/dev/.linuxbrew`; however this doesn't bring all the packages that I've installed. I can also `cp -r /path/to/prod/.linuxbrew /path/to/dev/.linuxbrew`; however this will result in a bunch of pathing problems with the installed packages.

Does anyone know of an easy way to achieve what I'd like without having to reinstall everything into my dev linuxbrew path? Thanks and cheers.

**Comment by sjackman** [comment]
Hi, James. No, I'm afraid it's not possible to copy a Linuxbrew installation from one location to another. Although some formulae are relocatable, not all are. The relocatable formulae contain the line `cellar :any`.

Consider installing Linuxbrew in `/home/linuxbrew/.linuxbrew/` if possible so that you can use precompiled binary packages (known as bottles) for the non-relocatable formula like `util-linux`, so that you won't have to build any common packages from source.

**Comment by jwhite007** [comment]
Thanks for the reply, Shaun.

I'm not sure what installing to `/home/linuxbrew/.linuxbrew` would give me over the path to which I'm installing now. Is there documentation on the differences?

Cheers

**Comment by sjackman** [comment]
The precompiled binary bottles of non-relocatable bottles can only be used if you install in `/home/linuxbrew/.linuxbrew`, otherwise they have to be built from source.
See below, but replace `/usr/local` which is for macOS with `/home/linuxbrew/.linuxbrew`.
+ http://docs.brew.sh/Installation.html#alternative-installs
+ http://docs.brew.sh/FAQ.html#why-do-you-compile-everything
+ http://docs.brew.sh/Bottles.html#cellar-cellar

**Comment by sjackman** [comment]
I've added this to the FAQ. https://github.com/Linuxbrew/brew/wiki/FAQ
