### ISSUE TITLE
systemd: error: conflicting types for 'lookup_errno'

### ISSUE THREAD

**Issue by parsibox** [Linuxbrew/brew#332]
https://gist.github.com/b213e0ef776596e915b8e778e687ec72

**Comment by sjackman** [comment]
```
In file included from src/basic/errno-list.c:31:0:
src/basic/errno-from-name.h:143:1: error: conflicting types for 'lookup_errno'
 lookup_errno (register const char *str, register size_t len)
 ^
src/basic/errno-list.c:27:33: note: previous declaration of 'lookup_errno' was here
 static const struct errno_name* lookup_errno(register const char *str,
                                 ^
make[2]: *** [Makefile:14175: src/basic/libbasic_la-errno-list.lo] Error 1
make[1]: *** [Makefile:18384: install-recursive] Error 1
make: *** [Makefile:19618: install] Error 2
```
https://gist.githubusercontent.com/anonymous/b213e0ef776596e915b8e778e687ec72/raw/86493c9b5b89e9bc03ce830eba200808f162a139/02.make

**Comment by sjackman** [comment]
Consider installing Linuxbrew in `/home/linuxbrew/.linuxbrew/` if possible so that you can use precompiled binary packages (known as bottles) for non-relocatable formula like `systemd`.

The precompiled binary bottles of non-relocatable bottles can only be used if you install in `/home/linuxbrew/.linuxbrew`, otherwise they have to be built from source. See the documentation below, but wherever it reads `/usr/local`, which is for macOS, read instead `/home/linuxbrew/.linuxbrew`.
+ http://docs.brew.sh/Installation.html#alternative-installs
+ http://docs.brew.sh/FAQ.html#why-do-you-compile-everything
+ http://docs.brew.sh/Bottles.html#cellar-cellar
