### ISSUE TITLE
Hardware::CPU.type should check `uname -m`

### ISSUE THREAD

**Issue by xu-cheng** [Linuxbrew/brew#336]
If running brew inside a Raspberry Pi docker container, `Hardware::CPU.type` will report incorrect arch type. In my case, it will return `intel` instead of `arm`. The is because `/etc/cpuinfo` will report the host CPU type. It would be better to check `uname -m` for better hardware detection, especially when the host and VM have different CPU architectures.

**Comment by sjackman** [comment]
It seems odd to me that `/proc/cpuinfo` should return the host CPU type rather than the emulated CPU type. Which VM is being used to emulate the ARM CPU?

**Comment by xu-cheng** [comment]
I use docker for Mac. https://www.docker.com/docker-mac

**Comment by xu-cheng** [comment]
More related doc: https://docs.docker.com/docker-for-mac/multi-arch/

**Comment by sjackman** [comment]
> Docker for Mac provides binfmt_misc multi architecture support, so you can run containers for different Linux architectures, such as arm, mips, ppc64le and even s390x.
This should just work without any configuration, but the containers you run need to have the appropriate qemu binary inside the container before you can do this. (See QEMU for more information.)

It uses QEMU with binfmt_misc. If I undestand correctly, that means it fires up a new QEMU instance for every ARM executable that is run, but runs scripts using the host environment. Without digging deeper, I guess that's why `/proc/cpuinfo` returns the CPU of the host environment.

**Comment by sjackman** [comment]
It's a bit of an unusual case, but I'd be okay merging a PR that checks whether either `uname -m` or `/proc/cpuinfo` says `arm`.
