### ISSUE TITLE
Error: glibc cannot be built with any available compilers.

### ISSUE THREAD

**Issue by emreerhan** [Linuxbrew/brew#363]
I installed linuxbrew on a fresh vm of centos7 where the only thing I had run prior was to install development tools:

`$ sudo yum groupinstall 'Development Tools'`

I have gcc installed as a result, however linuxbrew still tells me to install either gcc or clang through brew when it tries to get glibc:
```
==> Installing hello dependency: glibc
Error: glibc cannot be built with any available compilers.
```

Is this expected behaviour? Or is there something that has to be done to get linuxbrew to use tools already installed on the system?

**Comment by emreerhan** [comment]
By the way, I can't install gcc using brew because it has glibc as a dependency:

```
$ brew install gcc
==> Installing dependencies for gcc: glibc, xz, gmp, mpfr, libmpc, isl
==> Installing gcc dependency: glibc
Error: glibc cannot be built with any available compilers.
Install Clang or brew install gcc
```

So it's like a chicken and egg problem.

**Comment by ghost** [comment]
Having the same issue. Also running on CentOS7.

**Comment by sjackman** [comment]
Please report
```sh
brew --version
brew config
```
I believe this issue is resolved in the latest `master`, but that fix is not in the most recent stable release `brew 1.1.11`. It will be in the upcoming `brew 1.1.12`.
The work around is here:
https://github.com/Linuxbrew/brew/wiki/FAQ#error-glibc-cannot-be-built-with-any-available-compilers
