### ISSUE TITLE
Confusing guidance on installation location

### ISSUE THREAD

**Issue by vadi2** [Linuxbrew/brew#396]
Homepage says:

```
Linuxbrew is a fork of Homebrew, the macOS package manager, for Linux.

It can be installed in your home directory and does not require root access.
```

However when you're installing, it says that installing as a different user is recommended:

```
 vadi  ~  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install)"
-e:203: warning: Insecure world writable dir /home/vadi/Programs/Qt in PATH, mode 040777
==> Select the Linuxbrew installation directory
- Enter your password to install to /home/linuxbrew/.linuxbrew (recommended)
- Press Control-D to install to /home/vadi/.linuxbrew
- Press Control-C to cancel installation
```

This is confusing - which is recommended, installing in the home directory or as a different user?

**Comment by sjackman** [comment]
It can be installed in your home directory if necessary, but it's recommended to install in `/home/linuxbrew/.linuxbrew`.

The precompiled binary bottles of non-relocatable bottles can only be used if you install in `/home/linuxbrew/.linuxbrew`, otherwise they have to be built from source. See the documentation below, but wherever it reads `/usr/local`, which is for macOS, read instead `/home/linuxbrew/.linuxbrew`.
+ http://docs.brew.sh/Installation.html#alternative-installs
+ http://docs.brew.sh/FAQ.html#why-do-you-compile-everything
+ http://docs.brew.sh/Bottles.html#cellar-cellar
