### ISSUE TITLE
Pouring hangs on chrome os 

### ISSUE THREAD

**Issue by axk4545** [Linuxbrew/brew#41]
# Please follow the general troubleshooting steps first:
### Bug reports:

I got to installing hello for the first time and while installing it hung on pouring the bottle for hello. I decided to Ctrl C and continue with the next steps and got to the second attempt to run brew install where it again hung at pouring
I am on an Acer C720 with a Intel Celeron 2955U 1.4 GHz (Haswell micro-architecture) CPU and 2 GB of ram running ChromeOS 50.0.2661.91

**Comment by DoomHammer** [comment]
There was a problem with either lacking `file` installation or `file` in a wrong location. What does `which file` say on your system?

**Comment by DoomHammer** [comment]
Come to think of it, I see it has been partly fixed by https://github.com/Linuxbrew/brew/commit/bd49ee295451f0f1fb2fa5a5913aceabf22c580d . If you haven't been running `brew update` for a while this may be a good time.

**Comment by axk4545** [comment]
DoomHammer, I cannot get brew to install so I can run brew update. I am following this guide: https://github.com/Linuxbrew/linuxbrew/wiki/Chromebook-Install-Instructions
`which file` gives me `no file in $PATH`

**Comment by bw-yuhogg** [comment]
@abkahrs if you cannot run `brew update`, you can do `git pull` from inside your Homebrew directory to update it.

**Comment by sjackman** [comment]
@abkahrs Please install `file`.

``` sh
sudo apt-get install file
sudo yum install file
```

**Comment by axk4545** [comment]
@sjackman I am running this on chromeOS on a chromebook. I have no package manager.

**Comment by sjackman** [comment]
Ah, yes. Sorry. Piotr (@DoomHammer) is the Chrome expert here.
See `brewstrap`: https://github.com/DoomHammer/brewstrap/

**Comment by DoomHammer** [comment]
Am I? :)

I suggest trying https://github.com/DoomHammer/brewstrap/pull/7 for bootstrapping Linuxbrew on Chromebook. Some installer script might be in order, come to think of it.

**Comment by minektur** [comment]
pouring hanging means you need the 'file' command which chromeos does not have by default.  If you can get brew working enough to install stuff from source, then you can brew install homebrew-dupes/file-formula

When I've done this in the past, I had to avoid bottles (e.g. with brew install --build-from-source till I got the file-formula package built, which then makes bottles work.

**Comment by sjackman** [comment]
`-s` is a handy shortcut for `--build-from-source`

**Comment by axk4545** [comment]
@minektur could you expand on what you mean? I am not sure what steps I need or how far I need to get brew working since I haven't really worked with brew before.

**Comment by minektur** [comment]
@abkahrs there is a current dependency for installing bottles - the 'file' command must exist.  You'll find that the 'file'  command doesn't exist on chromeos.  They have really stripped things down and dont include it.  The dependency is not obvious, and 'brew install <some package you'd get from bottle>" it will just hang forever. 

 Because linuxbrew is a fork of homebrew which is built to install stuff on Mac OSX, such dependencies are subtle some times.  And also because of this there isn't a normal brew recipie for the file command in the normal brew repository because it would be installing a file that is a duplicate of an existing utility/command that already exists on macosx.  So there is a seperate set of recipies  that will install "dupes".  

On linux, and in this case for you on chromeos, it isn't a dupe at all, and once you install it somehow, then that brokenness with bottle-installs will go away.  So you have to build from source

You should just do this:

  brew install -s homebrew/dupes/file-formula

and then you shouldn't have that bug any more. (though linuxbrew is still a work-in-progress on chromeos...)

**Comment by axk4545** [comment]
Thank you all. I believe I have resolved the issue with the file install from source though that sgould be added to the chrome os install instructions
