### ISSUE TITLE
Introduce a HOMEBREW_ARCH environment variable to specify target microarchitecture

### ISSUE THREAD

**Issue by sjackman** [Linuxbrew/brew#42]
_From @eiennohito on April 22, 2016 5:16_

It is useful in scenarios when you have heterogenous grid of computers with different microarchitectures and want to build binaries that can be used everywhere.

Discussion is started in #1094.

_Copied from original issue: Linuxbrew/linuxbrew#1095_

**Comment by sjackman** [comment]
_From @eiennohito on May 16, 2016 4:13_

`-march=native` started to make shared installation unusable in our environment :(

**Comment by sjackman** [comment]
Sorry for the breakage, Arseny. Try the following workaround:

``` diff
diff --git a/Library/Homebrew/extend/ENV/std.rb b/Library/Homebrew/extend/ENV/std.rb
index 3d1b2a8..df84dcf 100644
--- a/Library/Homebrew/extend/ENV/std.rb
+++ b/Library/Homebrew/extend/ENV/std.rb
@@ -8,7 +8,7 @@ module Stdenv

   # @private
   SAFE_CFLAGS_FLAGS = "-w -pipe"
-  DEFAULT_FLAGS = OS.mac? ? "-march=core2 -msse4" : "-march=native"
+  DEFAULT_FLAGS = "-march=core2 -msse4"

   def self.extended(base)
     unless ORIGINAL_PATHS.include? HOMEBREW_PREFIX/"bin"
```

**Comment by sjackman** [comment]
I've added the requested `HOMEBREW_ARCH` environment variable. Just for my curiosity, what value are you planning to use? Linuxbrew bottles use `-march=core2`, so I'd suggest `HOMEBREW_ARCH=core2` if that works for you.

**Comment by eiennohito** [comment]
Thank you very much, this is great.

As a workaround I have temporarily made the `brew upgrade` job to execute on the oldest machine, but this should fix it. 

Regarding the value, it will be either `core2` or `nehalem`, I need to do a better hardware survey before deciding that.

**Comment by staticfloat** [comment]
Thanks for this Shaun.

To anyone frustrated with trying to compile software using linuxbrew on a Raspberry Pi, note that because Linuxbrew sends `-mcpu=native` to GCC, and GCC 4.9.2 suffers from [this bug](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=70132) in the current version of Raspbian, no software can be installed using Linuxbrew without setting `HOMEBREW_ARCH` to something other than `native`.  In the case of the Raspberry Pi 3, I have found `HOMEBREW_ARCH=armv8-a+crc` to work well.

**Comment by sjackman** [comment]
Thanks for the heads up, Elliot. How frustrating!
