### ISSUE TITLE
Can only run brew installed programs from one system

### ISSUE THREAD

**Issue by naymikm** [Linuxbrew/brew#44]
There is a couple systems that I can ssh between and use with my user profile at work. I installed some software with brew using system A and it works fine there but if I go to system B and run any brew installed programs I get this error 'Illegal instruction (core dumped)'. Running brew itself does not throw any errors on either system however just the brew installed software.

**Comment by bw-yuhogg** [comment]
"Illegal instruction" sounds to me like a binary problem. Are all of these systems the same architecture?

It makes sense that this wouldn't affect `brew` since it's run on a Ruby interpreter.

Can you try installing a program that runs on an interpreter and running that one of the other machines? `ant` might be a good choice.

**Comment by sjackman** [comment]
Hi, Marcus. The software is compiled for the processor on which you run `brew` using the GCC option `-march=native`. You have two options.
1. Always run `brew install` on the oldest machine that you want to use
2. Set the environment variable `export HOMEBREW_ARCH=core2`

`core2` should support your older computers, but if that doesn't work, you can setting it to a different value supported by the GCC `-march` option. For the possible values, see https://gcc.gnu.org/onlinedocs/gcc/x86-Options.html

After picking solution 1 or 2, run `brew reinstall formula` for the formula that is giving you trouble.
