### ISSUE TITLE
request: consider maintaining official zsh plugin

### ISSUE THREAD

**Issue by emanresusername** [Linuxbrew/brew#464]
# Please always follow these steps:
- [x] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at https://github.com/Linuxbrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew config` and `brew doctor` and included their output with your issue?

**Please note we will close your issue without comment if you delete or do not fill out the issue checklist and provide ALL the requested information.**

To help us debug your issue please explain:
- What you were trying to do (and why)
get a zsh plugin maintained by those more knowledgeable about the inner workings (because i hit a lot of non-intuitive quirky cases)
- What happened (include command output)
0. started with [`--force-bottle` not carrying through to dependencies when installed to `$HOME` directory](https://github.com/zpm-zsh/linuxbrew/pull/2)
0. recommended install wouldn't work with passwordless sudo
0. some (i think) hard coded paths in installer didn't work on systems with different set ups
  - e.g. on android ([termux](https://termux.com/)) [`#!/usr/bin/env`, `/bin/chgrp` etc don't work](https://wiki.termux.com/wiki/Main_Page#Prefixed_System). 
- What you expected to happen
0. bottle deps also work with the `$HOME` directory install
0. password not mandatory for recommended install
0. this one might be  pipe dream :sweat_smile: . but to the extent just something like `#!/usr/bin/env` could be `#!$PREFIX/usr/bin/env/` or just `#!env` it could at least progress closer to the bare, "this formula just doesn't work on the android architecture" type issues vs the current "maybe so, maybe no, but you can't get pass the shebang to find out" failures :) 
- Step-by-step reproduction instructions (by running `brew` commands)
0. do the fall back install to the `$HOME` dir and `brew install --force-bottle postgresql`
  - see several dependencies warn the `/home/linuxbrew/.linuxbrew/Cellar` directory is not there and they will build from source (but installing them directly with `--force-bottle` works fine
0. use the recommended ruby+curl install on a system where you can sudo with no password
0. use the recommended ruby+curl install on android

# Or propose a feature:
I guess for starters the proposal would be to copy [this](https://github.com/zpm-zsh/linuxbrew/pull/2) over here and fix any obvious red flags that jump out at you given you almost certainly know more about installing and working with linuxbrew than i do :)

Tried to fit the format as best i could, but it was a bit of a stretch :sweat_smile: 
glad to clarify anything unclear
this might go better in the [install repo](https://github.com/Linuxbrew/install), but didn't see any "new issue" option there? :confused:

**Comment by bw-yuhogg** [comment]
I think there's several issues here. I'll try to address them all; please clarify if I missed or misinterpreted something.

> get a zsh plugin maintained by those more knowledgeable about the inner workings (because i hit a lot of non-intuitive quirky cases)

I personally don't have the time or knowledge necessary to maintain this. One of the other Linuxbrew maintainers might want to, but no promises. Someone from upstream Homebrew might be willing to maintain this **if** there's nothing Linuxbrew-specific about it and it would work well on macOS.

> started with --force-bottle not carrying through to dependencies when installed to $HOME directory

Do you mean that `--force-bottle` only applies to the specified formula and not to its dependencies? If so, I suspect that's by design, and if you want to override it, you'll probably need to manually `brew install --force-bottle` all the dependencies that it's necessary for.

> recommended install wouldn't work with passwordless sudo

No, we don't have an issue tracker specific to the install repo. If you could open a new issue in this repo with more details about this problem, it would be greatly appreciated. If you figure out a solution, a PR would also be welcome.

> this one might be pipe dream 😅 . but to the extent just something like #!/usr/bin/env could be #!$PREFIX/usr/bin/env/ or just #!env it could at least progress closer to the bare, "this formula just doesn't work on the android architecture" type issues vs the current "maybe so, maybe no, but you can't get pass the shebang to find out" failures :)

Likewise, I think this warrants a separate issue. Again, a PR would be welcome if you figure out a solution.

**Comment by emanresusername** [comment]
yeah all that's fair
as far as the zsh plugin i don't think it'd be very much maintenance at all. essentially just putting the env var recommendations from the readme or in the post-install message in the file. 
Then for example if a decision to change from `$HOME/.linuxbrew` to `/home/linuxbrew/.linuxbrew` was made in this repo. A `s/OLDIR/NEWDIR/` type replacement here would also keep the plugin up to date (where a third party might not be aware and lag behind).

As for the other stuff, it's tough cause i notice these issues on initial set up just trying to get something else working usually, and then once i've finagled a working state i have no desire to revert back and address the hiccups individually 😅. i'll try to be better about raising issues/prs for stuff like that in the future

The immediate one i can think of is `privoxy` installs to `$(brew --prefix)/sbin` not  `$(brew --prefix)/bin` which isn't in the `PATH` recommendation in the  readme. i'll do a pull for that but that was the kind of thing i thought would be more likely to get noticed with a plugin maintained here than externally... but maybe that's more on the formula developer? 🤔

**Comment by bw-yuhogg** [comment]
Thanks for submitting the PR for putting `sbin` in the PATH recommendations!

> As for the other stuff, it's tough cause i notice these issues on initial set up just trying to get something else working usually, and then once i've finagled a working state i have no desire to revert back and address the hiccups individually 😅. i'll try to be better about raising issues/prs for stuff like that in the future

No worries, I'm glad it's in a working state for you now.

> yeah all that's fair
as far as the zsh plugin i don't think it'd be very much maintenance at all. essentially just putting the env var recommendations from the readme or in the post-install message in the file.
Then for example if a decision to change from $HOME/.linuxbrew to /home/linuxbrew/.linuxbrew was made in this repo. A s/OLDIR/NEWDIR/ type replacement here would also keep the plugin up to date (where a third party might not be aware and lag behind).

Individually, no. But unfortunately Linuxbrew already has a lot of moving parts which it's tough to keep in sync, partially because all the small individual time requirements add up and partially because it's just hard to remember everything to do.
