### ISSUE TITLE
Brewed GCC compilation failures after clean linuxbrew installation

### ISSUE THREAD

**Issue by eernst** [Linuxbrew/brew#488]
# Please always follow these steps:
- [x] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at https://github.com/Linuxbrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew config` and `brew doctor` and included their output with your issue?

[brew config](https://gist.github.com/eernst/6638e2cec88eff349376e31c330023a1)
[brew doctor](https://gist.github.com/eernst/14a7b2db65d769cb9de80b13da1d4752)

Beginning with a clean installation in /home/linuxbrew/.linuxbrew (after running the uninstall script, ```rm -r /home/linuxbrew/.linuxbrew``` and finally ```ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install)"```). After a ```brew install gcc```, I can ```brew install``` bottles, but can't install any packages from source with bottled gcc 5.3. 

```$ brew install -s hello ``` 

[gist-log](https://gist.github.com/eernst/08529ea25efcbc5ab5222001090ab25d)

```$ brew install -s stress```
[gist-log](https://gist.github.com/eernst/908110fa3b22339f5c7805afc0d74e50)

**Comment by iMichka** [comment]
```
lib/dirname-lgpl.c:86:1: internal compiler error: Illegal instruction
 }
 ^
0x2ad2f27da30f ???
	/tmp/glibc-20170824-4056-jtmpe6/glibc-2.23/signal/../sysdeps/unix/sysv/linux/x86_64/sigaction.c:0
0x2ad2f27c76ff __libc_start_main
	../csu/libc-start.c:289
```

or

```stress.c: In function 'hoghdd':
stress.c:765:1: internal compiler error: Illegal instruction
 }
 ^
0x2b147f15530f ???
	/tmp/glibc-20170824-4056-jtmpe6/glibc-2.23/signal/../sysdeps/unix/sysv/linux/x86_64/sigaction.c:0
0x2b147f1426ff __libc_start_main
	../csu/libc-start.c:289
Please submit a full bug report,
with preprocessed source if appropriate.
```

```
Host glibc: 2.17
/usr/bin/gcc: 4.8.5
glibc: 2.23
```

@sjackman some glibc mismatch here?

**Comment by sjackman** [comment]
> CPU: 64-core 64-bit westmere

https://gist.github.com/eernst/6638e2cec88eff349376e31c330023a1#file-gistfile1-txt-L13
https://en.wikipedia.org/wiki/Westmere_(microarchitecture)

My first guess is that your CPU is too old to run some bottle, possibly `glibc`. We've encountered this problem with `gmp` before. I haven't yet seen this problem with `glibc` 2.19, but perhaps it's a problem for `glibc` 2.23.

If you're comfortable debugging at the command line, to troubleshoot the problem, you can try something like…
```
ulimit -c unlimited
gcc-5 hello.c
gdb core*
x/i $pc
```

Otherwise try reinstalling the compiler toolchain from source rather than using bottles. Remove all installed packages with `brew remove $(brew list)`, and then run…
```sh
HOMEBREW_BUILD_FROM_SOURCE =1 brew install gcc
```

**Comment by eernst** [comment]
It looks like gmp could be the culprit. I tried the brew remove and source build as you suggested, and ```./configure``` fails for ```HOMEBREW_BUILD_FROM_SOURCE=1 brew install gmp``` ([gist-log](https://gist.github.com/4dbc04f99afb9dda3f11bb4277bdf5de)). 

However, ```./configure --enable-cxx``` successfully completes if I download the tarball and run manually ([configure stdout](https://gist.github.com/eernst/8a32b3d2fb30d0cf45725b839ec2fa02))

For some reason, the compiler test bombs out in the linuxbrew build context:
```
Last 15 lines from /home/eernst/.cache/Homebrew/Logs/gmp/01.configure:
checking for gcc-4.8 option to accept ISO C89... none needed
checking whether gcc-4.8 understands -c and -o together... yes
checking for gcc-4.8 option to accept ISO C99... -std=gnu99
checking for gcc-4.8 -std=gnu99 option to accept ISO Standard C... (cached) -std=gnu99
checking how to run the C preprocessor... gcc-4.8 -std=gnu99 -E
checking build system compiler gcc-4.8 -std=gnu99... yes
checking for build system preprocessor... gcc-4.8 -std=gnu99 -E
checking for build system executable suffix...
checking whether build system compiler is ANSI... yes
checking for build system compiler math library... -lm
checking whether we are using the GNU C++ compiler... yes
checking whether g++-4.8 accepts -g... yes
checking C++ compiler g++-4.8  -O2 -pedantic -fomit-frame-pointer -m64 -mtune=corei7 -march=corei7... no, program does not run
checking C++ compiler g++-4.8  -g -O2... no, program does not run
configure: error: C++ compiler not available, see config.log for details
```

... but is fine with the manual build...
```
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for gcc option to accept ISO C99... -std=gnu99
checking for gcc -std=gnu99 option to accept ISO Standard C... (cached) -std=gnu99
checking how to run the C preprocessor... gcc -std=gnu99 -E
checking build system compiler gcc -std=gnu99... yes
checking for build system preprocessor... gcc -std=gnu99 -E
checking for build system executable suffix...
checking whether build system compiler is ANSI... yes
checking for build system compiler math library... -lm
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking C++ compiler g++  -O2 -pedantic -fomit-frame-pointer -m64 -mtune=corei7 -march=corei7... yes
```

```$ diff /usr/bin/g++ /home/linuxbrew/.linuxbrew/bin/g++-4.8```
(no output)

**Comment by eernst** [comment]
After discovering this, I ran a ```brew remove $(brew list)``` again and a ```HOMEBREW_BUILD_FROM_SOURCE=1 brew install gmp``` to attempt to build gmp before some of the other dependencies of gcc. It turns out this succeeds:  [gist-logs](https://gist.github.com/45ccde7aedbb71d0ec2d1653fcf9264f) after installing m4 and xz as dependencies. 

Now, with 
```$ brew list```  
gmp  m4  xz

running ```HOMEBREW_BUILD_FROM_SOURCE=1 brew install gcc``` subsequently fails with the following at the ```make bootstrap``` stage:

```
In file included from /home/linuxbrew/.linuxbrew/include/features.h:392:0,
                 from /home/linuxbrew/.linuxbrew/include/stdio.h:27,
                 from ../../../../libgcc/../gcc/tsystem.h:87,
                 from ../../../../libgcc/libgcov.h:41,
                 from ../../../../libgcc/libgcov-merge.c:26:
/home/linuxbrew/.linuxbrew/include/gnu/stubs.h:7:27: fatal error: gnu/stubs-32.h: No such file or directory
compilation terminated.
```
[gist-logs](https://gist.github.com/ca0bf0e3279139a737a3cb494d1c0b97)

**Comment by sjackman** [comment]
Try…
```sh
export HOMEBREW_BUILD_FROM_SOURCE=1
brew install glibc
brew install gcc
```

**Comment by eernst** [comment]
Tried after a brew remove $(brew list). glibc installs successfully, gcc target fails at gmp with the same configure error as above.

**Comment by sjackman** [comment]
That looks like a bug. I've opened PR https://github.com/Linuxbrew/homebrew-core/pull/4246 to hopefully fix it. In the mean time, try…
```sh
HOMEBREW_BUILD_FROM_SOURCE=1 brew install https://raw.githubusercontent.com/sjackman/homebrew-core/gcc-disable-multilib/Formula/gcc.rb
```

**Comment by zijuexiansheng** [comment]
I've been having troubles compiling things using brewed gcc or compiling a new gcc too. I noticed several things that might be helpful.

1. It seems that the new version of binutils was compiled with a glibc 2.25 (see the comments of binutils.rb)
2. I tried different systems with glibc 2.17 locally, and gcc 4.4 or gcc 4.8. Somehow I think the glibc and binutils don't match and I can't make them match, even if I tried to compile a new one. So I can't compile a new gcc (many versions) successfully. If I used the brewed gcc, everything will be broken.
3. I'm trying to build a gcc 7.2 on my Ubuntu 17.04  that has glibc 2.24 and gcc 6.3.0. Since this system has higher version of glibc, brew didn't install another glibc for me. And now the compiling of my gcc 7.2 seems to be perfectly. I haven't encountered the problem I encountered at other machines yet.

**Comment by zijuexiansheng** [comment]
Just finished compiling the gcc 7.2. It works perfect.

![gcc-1](https://user-images.githubusercontent.com/3876598/30412281-517b1512-98e4-11e7-8167-fadb8ce94a1e.png)
![gcc-2](https://user-images.githubusercontent.com/3876598/30412283-5a970fc0-98e4-11e7-99b6-de260bb3d10e.png)
![gcc-3](https://user-images.githubusercontent.com/3876598/30412286-5dbafef0-98e4-11e7-933b-1d3d68ad8c24.png)

But still. I'm curious about how to fix the issues on my other machines. I don't have permission to upgrade those systems.

**Comment by eernst** [comment]
@sjackman With multilib disabled via the formula you provided, I'm now getting an error in make bootstrap while building gcc (for libgomp):
```
configure: updating cache ./config.cache
configure: error: unsupported system, cannot find sizeof (omp_lock_t)
make[2]: *** [configure-stage1-target-libgomp] Error 1
make[2]: Leaving directory `/tmp/gcc-20170913-27737-4mt8pv/gcc-5.3.0/build'
make[1]: *** [stage1-bubble] Error 2
```
[gist-logs](https://gist.github.com/eernst/7febe960d7a7314ed213042541f45101)

The issue remains that ```HOMEBREW_BUILD_FROM_SOURCE=1 brew install gcc``` fails at on a clean linuxbrew install at gmp on this machine - it appears that gmp needs to be built before glibc in order to make it all the way through the gcc dependencies and begin to compile gcc. 

I suspect all of this is resulting from a recent update to something in the gcc toolchain other than gcc, as I had a working gcc 5.3.0 last week, I believe, if not earlier this week. Unfortunately, I did a brew update without noting which basic libraries were updated.

**Comment by zijuexiansheng** [comment]
@eernst Did you tried to use gmp-6.1.1? Everything just crashed after I upgrade gmp-6.1.2 on an old machine. But it seems to work after I change back to gmp-6.1.1.

I used the following steps to use gmp-6.1.1.
1. `brew edit gmp`
2. change the everything that is `6.1.1` to `6.1.2`, and save it
3. `brew install gmp` or `brew reinstall gmp` if you've already installed it
4. when you see an error like sha256 is not correct, press `ctrl-C` to stop it from compiling from source
5. copy the actual sha256 value
6. `brew edit gmp`
7. in `bottle do`, change the sha256 value for the `:x86_64_linux` one, and save it
8. `brew install gmp` or `brew reinstall gmp` if you've already installed it

Then you can simply install gcc by `brew install gcc` and you don't have to compile it.

You can also try `brew install pkg-config` to see if gcc can compile it. If so, then it's probably the problem of the new gmp version. 

Since I also compiled other things with the system compiler, it's possible that there might be another reason. But this one is the closest reason I found. Hope this helps.

**Comment by sjackman** [comment]
> It seems that the new version of binutils was compiled with a glibc 2.25 (see the comments of binutils.rb)

`binutils` is compiled with `glibc` 2.5 (not 2.25) so that it can run on older systems with older versions of glibc.

**Comment by eernst** [comment]
Reverting to the gmp 6.1.1 bottle and using bottles for the rest of the gcc 5.3 toolchain works. I can successfully compile other packages from source afterward (hello, etc.). 

Perhaps this is a gmp-specific bug.

**Comment by iMichka** [comment]
Some other ideas. From the gmp website (just in case, I do not believe this is a really the problem here).

> The current stable release is 6.1.2, released 2016-12-16. 
Ryzen CPU caution: The AMD Ryzen CPUs sold in spring and early summer 2017 have serious bugs
which make any software run very unreliably. One experiences spurious segfaults and system hangs from building as well as running GMP. As of 2017-08-11 AMD has not disclosed the full ramifications of these bugs, and they refuse to recall faulty CPUs. Instead, they replace CPUs on a case-by-case basis after asking each customer to run in exhausting circles for a few weeks. They have invented a newspeak term for these bugs, Performance Marginality Problem.


There is also this old issue which looks similar: https://github.com/Homebrew/homebrew-versions/issues/1038

**Comment by sjackman** [comment]
The `gmp` formula has a problem wherein the bottle is compiled for the instruction set of the machine that it's being built on rather than the `core2` architecture that is usually the target instruction set of bottles. The host architecture may have changed when we updated from CircleCI 1.0 to 2.0.

**Comment by davidryderuk** [comment]
Just to confirm, I have the same issue as eernst, on a computer with the 'Intel Xeon E3-12xx v2 (Ivy Bridge)' processor. Reverting to the 6.1.1 bottle works for me as well.

**Comment by sjackman** [comment]
@davidryderuk Can you please report the output of `brew config`?

**Comment by davidryderuk** [comment]
I've uploaded the output from brew config [here](https://gist.github.com/davidryderuk/9f72b90bfc6cfbd130a21d08a133ec13).

**Comment by sjackman** [comment]
```
CPU: octa-core 64-bit ivybridge
```
https://gist.github.com/davidryderuk/9f72b90bfc6cfbd130a21d08a133ec13#file-gistfile1-txt-L12

Ivy Bridge is the sandybridge microarchitecture, which was released on 2011-01-09.
https://en.wikipedia.org/wiki/List_of_Intel_CPU_microarchitectures#Roadmap

It includes a lot of CPU instruction extensions:
```
x86-64, Intel 64
SSE, SSE2, SSE3, SSSE3, SSE4, SSE4.1, SSE4.2
AVX, TXT, VT-x, VT-d
```
https://en.wikipedia.org/wiki/Sandy_Bridge

If you're interested in helping troubleshoot this further and are comfortable using `gdb` to debug a core dump, you can follow these instructions above: https://github.com/Linuxbrew/brew/issues/488#issuecomment-328998824
to help determine which CPU instruction is causing the `Illegal instruction` error.

**Comment by davidryderuk** [comment]
Sorry, I'm struggling to get  the core dump. I can confirm a second, newer, but less capable computer is working correctly, without showing the same error. See [here](https://gist.github.com/davidryderuk/902761e55e1692eda6f41d18f6024d61).

**Comment by sjackman** [comment]
```
CPU: quad-core 64-bit broadwell
```
https://gist.github.com/davidryderuk/902761e55e1692eda6f41d18f6024d61#file-brew-config-output-broadwell-L12

Broadwell is the Haswell microarchitecture, the next one after Sandy Bridge, which was released on 2013-06-02.
https://en.wikipedia.org/wiki/Haswell_(microarchitecture)
Extensions
```
x86-64, Intel 64
SSE, SSE2, SSE3, SSSE3, SSE4, SSE4.1, SSE4.2
AVX, AVX2, TXT, and TSX (disabled via microcode, except for Haswell-EX)
VT-x, VT-d
```
Since Sandy Bridge, it gained AVX2. It's possible that the `gmp` 6.1.2 bottle is unintentionally using an AVX2 instruction. This is a bug. I don't yet know how to fix it.

**Comment by sjackman** [comment]
If anyone has the time and interest to look into the `gmp` issue, I'd appreciate a PR to fix the issue very much. I believe that the precompiled binary bottle may be using AVX2 instructions. It should not.

**Comment by sjackman** [comment]
The proper fix is to modify the formula to prevent it from using advanced instructions. That's going to require some work. In the mean time, I think we should either revert `gmp` to 6.1.1 and use the old bottle. Or, as a stop gap solution, build a bottle for `gmp` 6.1.2 on the oldest 64-bit Intel machine that we can get our hands on, or in a virtual machine emulating an old machine.

**Comment by sjackman** [comment]
I've hopefully resolved the issue with the `gmp` bottle with PR https://github.com/Linuxbrew/homebrew-core/pull/4399
Try `brew update && brew reinstall gmp`
If you get a SHA-256 error, delete the old cached bottle and try again.

**Comment by davidryderuk** [comment]
Thanks. That works for me with the ivy bridge computer.

**Comment by eernst** [comment]
Appears to be working fine on Westmere and Sandybridge. Thanks!

**Comment by zijuexiansheng** [comment]
Works on AMD Opteron(tm) Processor 6378

**Comment by sjackman** [comment]
Glad to hear it!
