### ISSUE TITLE
Problem installing on ScientificLinux/Fedora

### ISSUE THREAD

**Issue by weidenka** [Linuxbrew/brew#519]
I'm trying to install linuxbrew on ScientificLinux6 (a Fedora clone). I'm following the instructions given on the GitHub main page which seems to work. But when I'm trying to install packages which depend on `glibc` I get:
```
→brew install glibc
==> Installing glibc
Error: glibc cannot be built with any available compilers.
Install Clang or brew install gcc
```
`brew install gcc` leeds to the same problem since gcc depends on glibc. In `~/.linuxbrew/bin` are symlinks `gcc-4.4 -> /usr/bin/gcc`. Also `brew config` shows that the compiler is found:
``` 
→ brew config
HOMEBREW_VERSION: 1.3.6
ORIGIN: https://github.com/Linuxbrew/brew
HEAD: b39b60a4bfd51e5f2e83f5dc927cdb1f67310686
Last commit: 2 weeks ago
Core tap ORIGIN: https://github.com/Linuxbrew/homebrew-core
Core tap HEAD: adaa68524d703960cc4a599cc41f93526695e563
Core tap last commit: 18 hours ago
HOMEBREW_PREFIX: /home/user/.linuxbrew
HOMEBREW_REPOSITORY: /home/user/.linuxbrew/Homebrew
HOMEBREW_CELLAR: /home/user/.linuxbrew/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://linuxbrew.bintray.com
CPU: 16-core 64-bit 0x1009
Homebrew Ruby: 2.3.3 => /home/user/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: 3.4 build
Git: 1.8.5.6 => /home/user/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /home/user/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.0.0-p648/bin/ruby
Java: 1.6.0_39
Kernel: Linux 2.6.32-71.18.2.el6.x86_64 x86_64 GNU/Linux
OS: Scientific Linux release 6.7 (Carbon) (Carbon)
Host glibc: 2.12
/usr/bin/gcc: 4.4.7
glibc: N/A
gcc: N/A
xorg: N/A
```
I tried to set `HOMEBREW_BUILD_FROM_SOURCE=1` which made it possible to install some packages (but after a while another problem occurred, but this is a different problem). 

I post the problem here, since I do not think that this is a problem of the glibc tab. Any ideas what is the problem here?

**Comment by sjackman** [comment]
GCC ≥ 4.7 is required to build `glib` 2.23 from source Try following these instructions:
https://github.com/Linuxbrew/brew/wiki/CentOS6

Consider installing Linuxbrew in `/home/linuxbrew/.linuxbrew/` if possible so that you can use precompiled binary packages (known as bottles) for non-relocatable formula like `glibc`.

The precompiled binary bottles of non-relocatable bottles can only be used if you install in `/home/linuxbrew/.linuxbrew`, otherwise they have to be built from source. See the documentation below, but wherever it reads `/usr/local`, which is for macOS, read instead `/home/linuxbrew/.linuxbrew`.
+ http://docs.brew.sh/Installation.html#alternative-installs
+ http://docs.brew.sh/FAQ.html#why-do-you-compile-everything
+ http://docs.brew.sh/Bottles.html#cellar-cellar
