### ISSUE TITLE
[Feature suggestion] - ability to install linuxbrew via gem?

### ISSUE THREAD

**Issue by ghost** [Linuxbrew/brew#558]
Hello linuxbrew maintainers,

Is it planned - or in theory, possible - to use "gem" itself to install
linuxbrew? I am mostly asking for convenience e. g. "gem install linuxbrew".

The alternative ways to install linuxbrew work fine so no problem there.

Cheers for thinking about the linux users!

**Comment by sjackman** [comment]
HI, Robert. An interesting suggestion. As Linuxbrew is a fork of Homebrew, we don't usually add features to Linuxbrew that aren't present in Homebrew. We're currently working on merging Linuxbrew into Homebrew. Since Homebrew is usually installed into `/usr/local/…` and not the usual Gem path, I suspect that the answer is no, it's not possible. I could see potential for `gem install linuxbrew` installing a thin wrapper script `brew` that upon its first invocation, installs Linuxbrew in its usual location, and then after that, simply runs Linuxbrew.
