### ISSUE TITLE
no changelog for linuxbrew/homebrew-core unforked from homebrew/homebrew-core

### ISSUE THREAD

**Issue by timotheecour** [Linuxbrew/brew#641]
- [ ] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula please file this issue at Linuxbrew/homebrew-core: https://github.com/Linuxbrew/homebrew-core/issues/new. If it's a tap problem please file this issue at the tap.
- [ ] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew config` and `brew doctor` and included their output with your issue?

linuxbrew/homebrew-core used to be a fork from homebrew/homebrew-core (eg https://github.com/Linuxbrew/homebrew-core/issues/754 ) but it's now not showing as a fork.

Is there a changelog + rationale for this change?

https://github.com/Linuxbrew/brew/issues/601 seems to suggest it is still merged daily but curious since github doesn't report as a fork anymore

**Comment by iMichka** [comment]
The rationale was that upstream (homebrew-core) asked us to defork, because it was too confusing for the users and they got a lot of Linux related questions if I remember well.

I do not remember if we made any announcement regarding this, sorry.

I do the daily merges from homebrew-core into linuxbrew/homebrew-core. The process is the same as before, so nothing really changed here.
