### ISSUE TITLE
Something changes the process niceness to 10 during brew install

### ISSUE THREAD

**Issue by arkanoid87** [Linuxbrew/brew#697]
I am working into a clustered environment.
Brew install will takes ages if any configure or make is launched with niceness 10 instead of 0 without asking (I'm being eated by other users)

It is not an OS feature, i can launch multiple embedded stress -c 10 without experiencing the problem.

![screen shot 2018-05-04 at 05 23 38](https://user-images.githubusercontent.com/1446586/39612067-76e11318-4f5c-11e8-959c-f80e965e25dc.png)

**Comment by arkanoid87** [comment]
found
https://github.com/Linuxbrew/brew/blob/8bd8aa231cf2812ba7538f2e74b6c32e5fb567b8/Library/Homebrew/formula_installer.rb#L722

this line should be an option

**Comment by sjackman** [comment]
Linuxbrew/brew is a fork of Homebrew/brew that adds support for Linux. I'll close this issue, since it's not related specifically to Linux. If you had a proposed fix, you could open a PR at Homebrew/brew. In the mean time, you could simply delete `nice` from this line, commit the file, and from then on your installation of Linuxbrew should work as desired. `brew update` should retain your fix (I believe).

**Comment by arkanoid87** [comment]
Thank you

For other users, you also need to apply same change into the postinstall ruby call
