### ISSUE TITLE
Default install to user's home directory?

### ISSUE THREAD

**Issue by nextlogic-ono** [Linuxbrew/brew#762]
Linuxbrew tries to install to /home/linuxbrew/ but what is the reason for this decision?
It's kind of an odd place to put files under a non existent user's directory under /home.

It does seem to install under the current user's home but I'm not sure how to do this when the user does have the sudo privilege other than manually cloning the repo.

**Comment by jonchang** [comment]
You'll have to do the manual install if you'd like to install to a different directory under a user with sudo privileges. See the upstream [Homebrew's documentation](https://docs.brew.sh/Bottles) for why -- not all bottles are relocatable, so to make full use of our bottling infrastructure the default location is necessary.

**Comment by iMichka** [comment]
In more simple words: the precompiled binaires contain sometimes hard coded paths. We have chosen to go for /home/linuxbrew so you can use the bottles. Of course a manual install somewhere else is always possible.

**Comment by iMichka** [comment]
Closing here as this was more a question than a real issue.

**Comment by sjackman** [comment]
Here's my typical stock response, copied and pasted:

Consider installing Linuxbrew in `/home/linuxbrew/.linuxbrew/` if possible so that you can use precompiled binary packages (known as bottles) for non-relocatable formula like `util-linux`.
Another possible workaround for you is `brew install --force-bottle util-linux`, but no promises.

If it's an option for you, you could open a ticket with your information systems department to ask that they create a `linuxbrew` role account with home directory `/home/linuxbrew`.

The precompiled binary bottles of non-relocatable bottles can only be used if you install in `/home/linuxbrew/.linuxbrew`, otherwise they have to be built from source. See the documentation below. On macOS the default installation directory is `/usr/local`. On Linux the default installation directory is `/home/linuxbrew/.linuxbrew`.

+ http://docs.brew.sh/Installation.html#alternative-installs
+ http://docs.brew.sh/FAQ.html#why-do-you-compile-everything
+ http://docs.brew.sh/Bottles.html#cellar-cellar
