### ISSUE TITLE
cannot load such file -- os/linux/glibc

### ISSUE THREAD

**Issue by Vladyslav120604** [Linuxbrew/brew#936]
Please, help. This is my error:
```
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/home/vlad/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/glibc.rb:1:in `load_formula'
/home/vlad/.linuxbrew/Library/Homebrew/formulary.rb:21:in `module_eval'
/home/vlad/.linuxbrew/Library/Homebrew/formulary.rb:21:in `load_formula'
/home/vlad/.linuxbrew/Library/Homebrew/formulary.rb:34:in `load_formula_from_path'
/home/vlad/.linuxbrew/Library/Homebrew/formulary.rb:83:in `load_file'
/home/vlad/.linuxbrew/Library/Homebrew/formulary.rb:74:in `klass'
/home/vlad/.linuxbrew/Library/Homebrew/formulary.rb:70:in `get_formula'
/home/vlad/.linuxbrew/Library/Homebrew/formulary.rb:207:in `factory'
/home/vlad/.linuxbrew/Library/Homebrew/formula.rb:1186:in `[]'
/home/vlad/.linuxbrew/Library/Homebrew/cmd/install.rb:200:in `check_ld_so_symlink'
/home/vlad/.linuxbrew/Library/Homebrew/cmd/install.rb:213:in `perform_preinstall_checks'
/home/vlad/.linuxbrew/Library/Homebrew/cmd/install.rb:91:in `install'
/home/vlad/.linuxbrew/Library/brew.rb:84:in `<main>'
```

**Comment by sjackman** [comment]
Please surround copied-and-pasted logs with triple back ticks. See [GitHub Help / Quoting Code](https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code).

**Comment by sjackman** [comment]
Try…
```
brew update
brew vendor-install ruby
brew update
```

**Comment by sjackman** [comment]
If that doesn't help, please report the output of `brew config`.

**Comment by sjackman** [comment]
Consider installing Linuxbrew in `/home/linuxbrew/.linuxbrew/` if possible so that you can use precompiled binary packages (known as bottles) for non-relocatable formula like `util-linux`.
Another possible workaround for you is `brew install --force-bottle util-linux`, but no promises.

If it's an option for you, you could open a ticket with your information systems department to ask that they create a `linuxbrew` role account with home directory `/home/linuxbrew`.

The precompiled binary bottles of non-relocatable bottles can only be used if you install in `/home/linuxbrew/.linuxbrew`, otherwise they have to be built from source. See the documentation below. On macOS the default installation directory is `/usr/local`. On Linux the default installation directory is `/home/linuxbrew/.linuxbrew`.

+ http://docs.brew.sh/Installation.html#alternative-installs
+ http://docs.brew.sh/FAQ.html#why-do-you-compile-everything
+ http://docs.brew.sh/Bottles.html#cellar-cellar

**Comment by iMichka** [comment]
**Please note that we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

As there is way too much information missing here, I will close this issue. We can reopen it if you provide all the needed information
