### ISSUE TITLE
binutils: ld: unrecognized option '-plugin'

### ISSUE THREAD

**Issue by tseemann** [Linuxbrew/brew#96]
https://gist.github.com/1d81f9dfe2777cbc79cd705802f64d2c

Fresh linuxbrew install on RHEL 6

I don't think the brew doctor warnings are valid - /home is symlink.

**Comment by sjackman** [comment]
```
configure:4439: /gsfs2/home/u3/basmith/.linuxbrew/bin/gcc-5 -Os -w -pipe -march=native -isystem/gsfs2/home/u3/basmith/.linuxbrew/include -L/gsfs2/home/u3/basmith/.linuxbrew/lib -Wl,--dynamic-linker=/gsfs2/home/u3/basmith/.linuxbrew/lib/ld.so -Wl,-rpath,/gsfs2/home/u3/basmith/.linuxbrew/lib conftest.c  >&5
/usr/bin/ld: unrecognized option '-plugin'
```

https://gist.github.com/anonymous/1d81f9dfe2777cbc79cd705802f64d2c#file-config-log-L101

`/usr/bin/ld` is too old for the `gcc-5` provided by Linuxbrew. Try:

``` sh
brew remove gcc
brew install binutils
brew install gcc
```

**Comment by sjackman** [comment]
I just experienced this same issue myself after `brew update && brew upgrade`.
`configure: error: C compiler cannot create executables`
Upgrading `binutils` unlinks `binutils`, and then `gcc` no longer works because `binutils` is unlinked and it falls back to the host's `binutils`, which is too old.
This workaround worked for me:

``` sh
PATH=`brew --prefix binutils`/bin:$PATH brew upgrade binutils
```

Note that this issue will only exist while `binutils` is not bottled. I'm working on bottling `binutils` right now. It's bottling is special, because `binutils` is installed before `glibc`, so it has to be able to run on ancient versions of `glibc`. We support CentOS 5 glibc 2.5 and later.

**Comment by sjackman** [comment]
I've updated the `binutils` 2.27 bottle, which should resolve this issue.

**Comment by tseemann** [comment]
Thanks Shaun.
